source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TBHourMinutePickerView_Example', :exclusive => true do
  pod "TBHourMinutePickerView", :path => "../"
end

target 'TBHourMinutePickerView_Tests', :exclusive => true do
  pod "TBHourMinutePickerView", :path => "../"

  
end
